name: openf1

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo:27017
      ROLE: api
      OPENF1_BASE_URL: http://api:8000/
    depends_on:
      - mongo
      - mqtt



  mongo:
    image: "mongo:8"
    volumes:
      - mongo-data:/data/db

  mqtt:
    image: "eclipse-mosquitto:2.0.22"
    ports:
      - "1883:1883" # Standard MQTT
      - "8084:8084" # WebSockets
    volumes:
      - mqtt-data:/mosquitto/data
      - ./mqtt-config:/mosquitto/config

volumes:
  mongo-data:
  mqtt-data:
