"""The description of each attribute in the `API methods` section of the documentation."""


ATTRIBUTES_DESCRIPTIONS = {
    'date_start': 'The UTC starting date and time, in ISO 8601 format.',
    'date_end': 'The UTC ending date and time, in ISO 8601 format.',
    'driver_number': 'The unique number assigned to an F1 driver (cf. <a href="https://en.wikipedia.org/wiki/List_of_Formula_One_driver_numbers#Formula_One_driver_numbers" target="_blank">Wikipedia</a>).',
    'duration_sector_1': 'The time taken, in seconds, to complete the first sector of the lap.',
    'duration_sector_2': 'The time taken, in seconds, to complete the second sector of the lap.',
    'duration_sector_3': 'The time taken, in seconds, to complete the third sector of the lap.',
    'i1_speed': 'The speed of the car, in km/h, at the first intermediate point on the track.',
    'i2_speed': 'The speed of the car, in km/h, at the second intermediate point on the track.',
    'is_pit_out_lap': 'A boolean value indicating whether the lap is an "out lap" from the pit (`true` if it is, `false` otherwise).',
    'lap_duration': 'The total time taken, in seconds, to complete the entire lap.',
    'lap_number': 'The sequential number of the lap within the session (starts at 1).',
    'meeting_key': 'The unique identifier for the meeting. Use `latest` to identify the latest or current meeting.',
    'segments_sector_1': 'A list of values representing the "mini-sectors" within the first sector (see mapping table below).',
    'segments_sector_2': 'A list of values representing the "mini-sectors" within the second sector (see mapping table below).',
    'segments_sector_3': 'A list of values representing the "mini-sectors" within the third sector (see mapping table below).',
    'session_key': 'The unique identifier for the session. Use `latest` to identify the latest or current session.',
    'st_speed': 'The speed of the car, in km/h, at the speed trap, which is a specific point on the track where the highest speeds are usually recorded.',
    'date': 'The UTC date and time, in ISO 8601 format.',
    'x': "The 'x' value in a 3D Cartesian coordinate system representing the current approximate location of the car on the track.",
    'y': "The 'y' value in a 3D Cartesian coordinate system representing the current approximate location of the car on the track.",
    'z': "The 'z' value in a 3D Cartesian coordinate system representing the current approximate location of the car on the track.",
    'circuit_key': 'The unique identifier for the circuit where the event takes place.',
    'circuit_short_name': 'The short or common name of the circuit where the event takes place.',
    'country_code': 'A code that uniquely identifies the country.',
    'country_key': 'The unique identifier for the country where the event takes place.',
    'country_name': 'The full name of the country where the event takes place.',
    'gmt_offset': 'The difference in hours and minutes between local time at the location of the event and Greenwich Mean Time (GMT).',
    'location': 'The city or geographical location where the event takes place.',
    'session_name': 'The name of the session (`Practice 1`, `Qualifying`, `Race`, ...).',
    'session_type': 'The type of the session (`Practice`, `Qualifying`, `Race`, ...).',
    'year': 'The year the event takes place.',
    'compound': 'The specific compound of tyre used during the stint (`SOFT`, `MEDIUM`, `HARD`, ...).',
    'stint_number': 'The sequential number of the stint within the session (starts at 1).',
    'lap_start': 'Number of the initial lap in this stint (starts at 1).',
    'lap_end': 'Number of the last completed lap in this stint.',
    'tyre_age_at_start': 'The age of the tyres at the start of the stint, in laps completed.',
    'recording_url': 'URL of the radio recording.',
    'meeting_name': 'The name of the meeting.',
    "meeting_official_name": 'The official name of the meeting.',
    'broadcast_name': "The driver's name, as displayed on TV.",
    'first_name': "The driver's first name.",
    'full_name': "The driver's full name.",
    'headshot_url': "URL of the driver's face photo.",
    'last_name': "The driver's last name.",
    'team_colour': "The hexadecimal color value (RRGGBB) of the driver's team.",
    'team_name': "Name of the driver's team.",
    'name_acronym': "Three-letter acronym of the driver's name.",
    'rpm': 'Revolutions per minute of the engine.',
    'speed': 'Velocity of the car in km/h.',
    'n_gear': "Current gear selection, ranging from 1 to 8. `0` indicates neutral or no gear engaged.",
    'throttle': 'Percentage of maximum engine power being used.',
    'drs': 'The Drag Reduction System (DRS) status (see mapping table below).',
    'brake': "Whether the brake pedal is pressed (`100`) or not (`0`).",
    'air_temperature': 'Air temperature (°C).',
    'humidity': 'Relative humidity (%).',
    'pressure': 'Air pressure (mbar).',
    'rainfall': 'Whether there is rainfall.',
    'track_temperature': 'Track temperature (°C).',
    'wind_direction': 'Wind direction (°), from 0° to 359°.',
    'wind_speed': 'Wind speed (m/s).',
    'category': 'The category of the event (`CarEvent`, `Drs`, `Flag`, `SafetyCar`, ...).', 
    'flag': 'Type of flag displayed (`GREEN`, `YELLOW`, `DOUBLE YELLOW`, `CHEQUERED`, ...).',
    'message': 'Description of the event or action.',
    'scope': 'The scope of the event (`Track`, `Driver`, `Sector`, ...).',
    'sector': 'Segment ("mini-sector") of the track where the event occurred? (starts at 1).',
    'position': 'Position of the driver (starts at 1).',
    'gap_to_leader': 'The time gap to the race leader in seconds, `+1 LAP` if lapped, or `null` for the race leader.',
    'interval': 'The time gap to the car ahead in seconds, `+1 LAP` if lapped, or `null` for the race leader.',
    'pit_duration': 'The time spent in the pit, from entering to leaving the pit lane, in seconds.',
}
